routes/contact.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user
from database.models.contact import Contact
from database.models.user import User

contact_route = Blueprint('contact', __name__)

'''
    - /contact/                 (GET) Renderizar um formulário para criar um contact
    - /contact/                 (POST) Insere um contact
    - /contact/all              (GET) Listar os contacts
    - /contact/<id>             (GET) Obter os dados de um contact   
    - /contact/<id>/edit        (GET) Renderizar um formulário para editar um contact
    - /contact/<id>/update      (PUT) Atualizar os dados de um contact
    - /contact/<id>/warning     (GET) Renderizar um formulário para editar um contact
    - /contact/<id>/delete      (DELETE) Deleta o registro do contact  
'''

@contact_route.route('/', methods=['GET', 'POST'])
def render_form():
    if not current_user.is_authenticated:
        return redirect(url_for('user.login'))
    from forms.contact import ContactForm
    form = ContactForm()
    
    if form.validate_on_submit():
        form.save()
        contacts = Contact.select().where(Contact.id_user == current_user)
        return render_template('contacts_list.html', contacts=contacts) 

    return render_template('form_contact.html', form=form)


@contact_route.route('/all', methods=['GET'])
def list_contacts():
    if not current_user.is_authenticated:
        return redirect(url_for('user.login'))
    
    contacts = Contact.select().where(Contact.id_user == current_user)
    return render_template('contacts_list.html', contacts=contacts)


@contact_route.route('/<int:id_contact>/edit')
def edit_contact(id_contact):
    if not current_user.is_authenticated:
        return redirect(url_for('user.login'))
    from forms.contact import ContactForm
    form = ContactForm()
    contact = Contact.get_by_id(id_contact)
    return render_template("form_contact.html", form=form, contact=contact)


@contact_route.route('/<int:id_contact>/update', methods=['PUT'])
def update_contact(id_contact):
    if not current_user.is_authenticated:
        return redirect(url_for('user.login'))
    from forms.contact import ContactForm
    form = ContactForm()
    
    if form.validate_on_submit():
        contacts = Contact.select().where(Contact.id_user == current_user)
        form.edit_save()
        return render_template('contacts_list.html', contacts=contacts)


@contact_route.route('/<int:id_contact>/warning')
def warning_contact(id_contact):
    if not current_user.is_authenticated:
        return redirect(url_for('user.login'))
    contact = Contact.get_by_id(id_contact)
    return render_template("contact_delete.html", contact=contact)


@contact_route.route('/<int:id_contact>/delete', methods=['DELETE'])
def delete_contact(id_contact):
    if not current_user.is_authenticated:
        return redirect(url_for('user.login'))
    
    contact_delete = Contact.delete().where(Contact.id_user == current_user).where(Contact.id == id_contact)
    contact_delete.execute()
    
    contacts = Contact.select().where(Contact.id_user == current_user)
    return render_template('contacts_list.html', contacts=contacts)

routes/control.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user
from database.models.nature import Nature

control_route = Blueprint('control', __name__)

'''
    - /control/                 (GET) Renderizar um formulário para criar um controle
    - /control/                 (POST) Insere um controle
    - /control/all              (GET) Listar os controles
    - /control/<id>             (GET) Obter os dados de um controle   
    - /control/<id>/edit        (GET) Renderizar um formulário para editar um controle
    - /control/<id>/update      (PUT) Atualizar os dados de um controle
    - /control/<id>/delete      (DELETE) Deleta o registro do controle  
    - /control/<id>/moves       (GET) Lista todos os movimentos para o controle específico 
'''

@control_route.route('/', methods=['GET', 'POST'])
def render_form():
    if not current_user.is_authenticated:
        return redirect(url_for('user.login'))
    from forms.control import ControlForm
    form = ControlForm()
    
    if form.validate_on_submit():
        form.save()
        return redirect(url_for('home.render_home'))

    return render_template('form_control.html', form=form)

routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint('home', __name__)

@home_route.route('/')
def render_home():
    return render_template('home.html')

@home_route.route('/appbar')
def render_appbar():
    return render_template('appbar.html')

routes/nature.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user
from database.models.nature import Nature
from database.models.user import User

nature_route = Blueprint('nature', __name__)

'''
    - /nature/                 (GET) Renderizar um formulário para criar um nature
    - /nature/                 (POST) Insere um nature
    - /nature/all              (GET) Listar os natures
    - /nature/<id>             (GET) Obter os dados de um nature   
    - /nature/<id>/edit        (GET) Renderizar um formulário para editar um nature
    - /nature/<id>/update      (PUT) Atualizar os dados de um nature
    - /nature/<id>/warning     (GET) Renderizar um formulário para editar um nature
    - /nature/<id>/delete      (DELETE) Deleta o registro do nature  
'''

@nature_route.route('/', methods=['GET', 'POST'])
def render_form():
    if not current_user.is_authenticated:
        return redirect(url_for('user.login'))
    from forms.nature import NatureForm
    form = NatureForm()
    
    if form.validate_on_submit():
        form.save()
        natures = Nature.select().where(Nature.id_user == current_user)
        return render_template('natures_list.html', natures=natures) 

    return render_template('form_nature.html', form=form)


@nature_route.route('/all', methods=['GET'])
def list_natures():
    if not current_user.is_authenticated:
        return redirect(url_for('user.login'))
    
    natures = Nature.select().where(Nature.id_user == current_user)
    return render_template('natures_list.html', natures=natures)


@nature_route.route('/<int:id_nature>/edit')
def edit_nature(id_nature):
    if not current_user.is_authenticated:
        return redirect(url_for('user.login'))
    from forms.nature import NatureForm
    form = NatureForm()
    nature = Nature.get_by_id(id_nature)
    return render_template("form_nature.html", form=form, nature=nature)


@nature_route.route('/<int:id_nature>/update', methods=['PUT'])
def update_nature(id_nature):
    if not current_user.is_authenticated:
        return redirect(url_for('user.login'))
    from forms.nature import NatureForm
    form = NatureForm()
    
    if form.validate_on_submit():
        natures = Nature.select().where(Nature.id_user == current_user)
        form.edit_save()
        return render_template('natures_list.html', natures=natures)


@nature_route.route('/<int:id_nature>/warning')
def warning_nature(id_nature):
    if not current_user.is_authenticated:
        return redirect(url_for('user.login'))
    nature = Nature.get_by_id(id_nature)
    return render_template("nature_delete.html", nature=nature)


@nature_route.route('/<int:id_nature>/delete', methods=['DELETE'])
def delete_nature(id_nature):
    if not current_user.is_authenticated:
        return redirect(url_for('user.login'))
    
    nature_delete = Nature.delete().where(Nature.id_user == current_user).where(Nature.id == id_nature)
    nature_delete.execute()
    
    natures = Nature.select().where(Nature.id_user == current_user)
    return render_template('natures_list.html', natures=natures)

routes/user.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_user, logout_user, current_user
from wtforms.validators import ValidationError

user_route = Blueprint('user', __name__)

'''
    /user/register/              GET - Renderiza o form para registro de novos usuários
    /user/register/              POST - Envia dados do novo usuário registrado
    /user/login/                 GET - Renderiza o form para login de usuário
    /user/login/                 POST - Envia dados da tentativa de login do usuário
    /user/logout/                GET - Faz o logout do usuário logado
'''
    

@user_route.route('/register', methods=['GET', 'POST'])
def register_user():
    from forms.register_user import RegisterForm
    form = RegisterForm()

    
    if form.validate_on_submit():
        user = form.save()
        login_user(user, remember=True)
        return redirect(url_for('home.render_home'))
    elif 'email' in form.errors and 'Email de usuário já cadastrado' in form.errors['email']:
        flash('Email de usuário já cadastrado!')
        return redirect(url_for('user.register_user'))
    elif 'confirm_password' in form.errors and 'Field must be equal to password.' in form.errors['confirm_password']:
        flash('As senhas não são iguais!')
        return redirect(url_for('user.register_user'))
    elif 'password' in form.errors and 'Invalid input.' in form.errors['password']:
        flash('''
A senha deve conter:
- Pelo menos 10 caracteres
- Pelo menos 1 letra maiúscula
- Pelo menos 1 letra minúscula
- Pelo menos 1 número''')
        return redirect(url_for('user.register_user'))

    return render_template('form_register_user.html', form=form)

@user_route.route('/login', methods=['GET', 'POST'])
def login():
    from forms.login_user import LoginForm
    form = LoginForm()

    try:
        if form.validate_on_submit():
            user = form.login()
            login_user(user, remember=True)
            return redirect(url_for('home.render_home'))
    except ValidationError:
        flash('Usuário ou senha incorreta!')
        return redirect(url_for('user.login'))

    return render_template('form_login_user.html', form=form)

@user_route.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('user.login'))

templates/appbar.html
<nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('home.render_home') }}">Home</a>
        {% if current_user.is_authenticated %}
            <div>
                <a class="btn btn-success">{{ current_user.name_user }}</a>
                <a href="{{ url_for('user.logout') }}" class="btn btn-danger">Sair</a>
            </div>
        {% else %}
            <div>
                <a href="{{ url_for('user.register_user') }}" class="btn btn-primary">Cadastre-se</a>
                <a href="{{ url_for('user.login') }}" class="btn btn-primary">Login</a>
            </div>
        {% endif %}
    </div>
  </nav>

templates/contact_delete.html
<div class="modal-header">
    <h5 class="modal-title">Deletar contato</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
</div>

<div class="mt-3 mb-3">
    Deseja excluir permanentemente o contato {{ contact.name }}?
</div>

<div class="modal-footer">
    <button 
        class="btn btn-danger"
        hx-delete="{{ url_for('contact.delete_contact', id_contact=contact.id) }}"
        hx-target="#contact-list"
        hx-swap="outerHTML"
        data-bs-dismiss="modal">
        Excluir
    </button>
    <button class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
</div>

templates/estimate_import.html
<div class="modal-header">
    <h5 class="modal-title">Importar estimativas</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
</div>

<div class="mt-3 mb-3">
    <p>Importar as estimativas substituirá as atuais!</p>
    <ul class="list-group">
        {% for control in controls %}
        <li class="list-group-item">
            <div class="col-11 form-floating mx-auto"
                style="display: flex;justify-content: space-between;align-items: center;">
                <span>{{ control.month_control }} - {{ control.year_control }}</span>
                <a 
                    hx-get="{{ url_for('estimate.import_estimate_save', id_control=id_control, id_new_control=control.id) }}"
                    hx-target="#estimate-list" hx-swap="outerHTML"
                    data-bs-toggle="modal" data-bs-target="#estimate-modal" 
                    class="btn btn-primary bi bi-check">
                </a>
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

<div class="modal-footer">
    <button class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
</div>

templates/estimate_list.html
{% extends 'index.html' %}

{% block content %}

<div class="container-fluid mt-2" id="estimate-list">

    <div class="row col-12 col-md-4 col-lg-4 p-2 rounde border shadow">
        <h3 class="text-start ms-4 h5 mb-3 mt-1">Estimativas</h3>
        <ul class="list-group">
            {% for estimate in estimates %}
            <li class="list-group-item">
                <div class="col-11 form-floating mx-auto"
                    style="display: flex;justify-content: space-between;align-items: center;">
                    <span>{{ estimate['name_nature'] }}</span>
                    <span>R$ {{ estimate['value_estimate'] }} </span>
                </div>
            </li>
            {% endfor %}
        </ul>
        <div class="input-two-line mt-3">
            <a hx-get="{{ url_for('estimate.import_estimates', id_control=id_control) }}" class="btn btn-primary col-5"
                hx-target="#modal-content" data-bs-toggle="modal" data-bs-target="#estimate-modal">
                Importar
            </a>
            <a hx-get="{{ url_for('estimate.adjust_estimate', id_control=id_control ) }}" class="btn btn-primary col-5"
                hx-target="#modal-content" data-bs-toggle="modal" data-bs-target="#estimate-modal">
                Ajustar
            </a>
        </div>
    </div>
</div>

<div class="modal fade" id="estimate-modal" tabindex="-1">
    <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-body" id="modal-content"></div>
        </div>
    </div>
</div>

{% endblock %}

templates/estimate_natures.html
{% extends 'index.html' %}

{% block content %}

<div style="display: flex;justify-content: space-between;">
    <h3 class="text-start ms-4 h5 mb-3 mt-1">Ajustar estimativas</h3>
    <a class="btn-close" href="{{ url_for('estimate.render_nature_list', id_control=id_control) }}"></a>
</div>

{% for form in forms %}
<form>
    <div class="col-11 form-floating mb-3 mx-auto"
        style="display: flex;justify-content: space-around;align-items: center;">
        {{ form.hidden_tag() }}
        {{ form.id_estimate }}
        {{ form.value_nature(class='form-control me-2', id="floatingNature", placeholder="450.50") }}
        {{ form.value_nature.label(for="floatingNature") }}
        <button hx-post="{{ url_for('estimate.adjust_estimate', id_control=id_control) }}" hx-target="#modal-content"
            class="btn btn-primary bi bi-check me-2" style="height: 50%;">
        </button>
    </div>
</form>
{% endfor %}

{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="alert alert-success alert-dismissible fade show col-10 mx-auto" role="alert">
    {% for message in messages %}
    <p>{{ message }}</p>
    {% endfor %}
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
</div>
{% endif %}
{% endwith %}

<div class="col-11 mx-auto" style="display: flex;justify-content: space-between;">
    <a 
        href="{{ url_for('nature.list_natures') }}" 
        class="btn btn-primary col-6">
        Gerenciar Naturezas
    </a>
    <a 
        class="btn btn-secondary col-4" 
        href="{{ url_for('estimate.render_nature_list', id_control=id_control) }}">
        Fechar
    </a>
</div>

{% endblock %}

templates/form_contact.html
<div class="modal-header">
    <h5 class="modal-title">
        {% if contact %}
        Editar Contato
        {% else %}
        Cadastrar Contato
        {% endif %}
    </h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
</div>
<form
    hx-target="#contact-list"
    hx-swap="outerHTML"
    {% if contact %}
        hx-put="{{ url_for('contact.update_contact', id_contact=contact.id) }}"
    {% else %}
        hx-post="{{ url_for('contact.render_form') }}"
    {% endif %}>
    {{ form.csrf_token }}

    {% if contact %}
    {{form.id(value=contact.id)}}
    {% endif %}

    <div class="col-11 form-floating mb-3 mx-auto">
        {{ form.name(class='form-control mt-3', id="floatingContact", placeholder="João Silva", value=contact.name_contact if contact else '') }}
        {{ form.name.label(for="floatingContact") }}
    </div>

    <div class="col-11 form-floating mb-3 mx-auto">
        {{ form.description(class='form-control', id="floatingDescription", placeholder="Descrição de teste", value=contact.description_contact if contact else '') }}
        {{ form.description.label(for="floatingDescription") }}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
        <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">
            {% if contact %}
                Salvar
            {% else %}    
                Cadastrar
            {% endif %}
        </button>
    </div>
</form>

templates/form_control.html
<div class="container">

    <div class="row col-12 col-md-4 col-lg-3 p-2 rounde border shadow">
            <h3 class="text-start ms-4 h5 mb-3 mt-1">Cadastrar mês de controle</h3>
        <form action="{{ url_for('control.render_form') }}" method="post">
            {{ form.csrf_token }}

            <div class="col-11 mb-3 mx-auto">
                {{ form.month_year(class='form-control') }}
            </div>

            <div class="input-two-line">
                {{ form.btn_submit(class='btn btn-primary col-5 mb-3') }}
                <a href="{{ url_for('home.render_home') }}" class="btn btn-danger col-5 mb-3">Cancelar</a>
            </div>
        </form>
    </div>

</div>

templates/form_login_user.html
{% extends 'index.html' %}

{% block content %}

<div id="div-form-login" class="container">


    <div class="row col-12 col-md-8 col-lg-6 p-2 rounde border shadow">
            <h3 class="text-start ms-4 h5 mb-3 mt-1">Entrar</h3>
        <form action="{{ url_for('user.login') }}" method="post" id="login_user_form">
            {{ form.csrf_token }}

            <div class="col-11 form-floating mb-3 mx-auto">
                {{ form.email(class='form-control', id="floatingEmail", placeholder="usuario@teste.com") }}
                {{ form.email.label(for="floatingEmail") }}
            </div>

            <div class="col-11 form-floating mb-3 mx-auto">
                {{ form.password(class='form-control', id="floatingPassword", placeholder="Senha123") }}
                {{ form.password.label(for="floatingPassword") }}
            </div>

            <div class="input-two-line">
                {{ form.btn_submit(class='btn btn-primary col-5 mb-3') }}
                <a href="{{ url_for('home.render_home') }}" class="btn btn-danger col-5 mb-3">Cancelar</a>
            </div>
        </form>

        <div id="warning-login" class="mb-3 col-11 col-md-8 col-lg-6 bg-warning text-center mx-auto">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
                    {% for message in messages %}
                    <p>{{ message }}</p>
                    {% endfor %}
            {% endif %}
            {% endwith %}
        </div>

        <hr class="mb-3 col-9 mx-auto">

        <p class="text-center mb-0">Ainda não possui login?</p> 
        <a class="text-center mb-3" href="{{ url_for('user.register_user') }}">Faça seu cadastro!</a>
    </div>


</div>


{% endblock %}

templates/form_nature.html
<div class="modal-header">
    <h5 class="modal-title">
        {% if nature %}
        Editar Natureza
        {% else %}
        Cadastrar Natureza
        {% endif %}
    </h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
</div>
<form
    hx-target="#nature-list"
    hx-swap="outerHTML"
    {% if nature %}
        hx-put="{{ url_for('nature.update_nature', id_nature=nature.id) }}"
    {% else %}
        hx-post="{{ url_for('nature.render_form') }}"
    {% endif %}>
    {{ form.csrf_token }}

    {% if nature %}
    {{form.id(value=nature.id)}}
    {% endif %}

    <div class="col-11 form-floating mb-3 mx-auto">
        {{ form.name(class='form-control', id="floatingNature", placeholder="Manutenção", value=nature.name_nature if nature else '') }}
        {{ form.name.label(for="floatingNature") }}
    </div>

    <div class="col-11 form-floating mb-3 mx-auto">
        {{ form.description(class='form-control', id="floatingDescription", placeholder="Descrição de teste", value=nature.description_nature if nature else '') }}
        {{ form.description.label(for="floatingDescription") }}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
        <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">
            {% if nature %}
                Salvar
            {% else %}    
                Cadastrar
            {% endif %}
        </button>
    </div>
</form>

templates/form_register_user.html
{% extends 'index.html' %}

{% block content %}

<div id="div-form-register" class="container">

    <div class="row col-12 col-md-8 col-lg-6 p-2 rounde border shadow">
        <h3 class="text-start ms-4 h5 mb-3 mt-1">Cadastrar-se</h3>
        <form action="{{ url_for('user.register_user') }}" method="post" id="register_user_form">
            {{ form.csrf_token }}

            <div class="col-11 form-floating mb-3 mx-auto">
                {{ form.email(class='form-control', id="floatingEmail", placeholder="usuario@teste.com") }}
                {{ form.email.label(for="floatingEmail") }}
            </div>

            <div class="col-11 form-floating mb-3 mx-auto">
                {{ form.name(class='form-control', id="floatingName", placeholder="João") }}
                {{ form.name.label(for="floatingName") }}
            </div>

            <div class="input-two-line">
                <div class="col-5 form-floating mb-3">
                    {{ form.password(class='form-control', id="floatingPassword", placeholder="Senha123") }}
                    {{ form.password.label(for="floatingPassword") }}
                </div>

                <div class="form-floating mb-3 col-5">
                    {{ form.confirm_password(class='form-control', id="floatingConfirmPassword", placeholder="Senha123")
                    }}
                    {{ form.confirm_password.label(for="floatingConfirmPassword") }}
                </div>
            </div>

            <div class="input-two-line">
                {{ form.btn_submit(class='btn btn-primary col-5 mb-3') }}
                <a href="{{ url_for('home.render_home') }}" class="btn btn-danger col-5 mb-3">Cancelar</a>
            </div>

        </form>

        <div id="warning-register" class="mb-3 col-12 col-md-10 col-lg-8 bg-warning text-center mx-auto">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for message in messages %}
            <pre class="text-start">{{ message }}</pre class="text">
                    {% endfor %}
            {% endif %}
            {% endwith %}
        </div>

        <hr class="mb-3 col-9 mx-auto">

        <p class="text-center mb-0">Já possui cadastro?</p> 
        <a class="text-center mb-1" href="{{ url_for('user.login') }}">Faça seu login!</a>
    </div>


</div>


{% endblock %}

templates/home.html
{% extends 'index.html' %}

{% block content %}

<div hx-get="{{ url_for('home.render_appbar') }}" hx-trigger="load"></div>

<div class="container">

    

</div>


{% endblock %}

templates/index.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Controle Financeiro</title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

  <script src="https://unpkg.com/htmx.org@2.0.2"
    integrity="sha384-Y7hw+L/jvKeWIRRkqWYfPcvVxHzVzn5REgzbawhxAuQGwX1XWe70vji+VSeHOThJ"
    crossorigin="anonymous"></script>
</head>

<body>

    {% block content %} {% endblock %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
</body>

</html>

templates/nature_delete.html
<div class="modal-header">
    <h5 class="modal-title">Deletar natureza</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
</div>

<div class="mt-3 mb-3">
    Deseja excluir permanentemente a natureza {{ nature.name }}?
</div>

<div class="modal-footer">
    <button 
        class="btn btn-danger"
        hx-delete="{{ url_for('nature.delete_nature', id_nature=nature.id) }}"
        hx-target="#nature-list"
        hx-swap="outerHTML"
        data-bs-dismiss="modal">
        Excluir
    </button>
    <button class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
</div>

templates/natures_list.html
{% extends 'index.html' %}

{% block content %}

<div class="container-fluid mt-2" id="nature-list">

    <div class="row col-12 col-md-4 col-lg-4 p-2 rounde border shadow">
        <h3 class="text-start ms-4 h5 mb-3 mt-1">Naturezas</h3>
        <ul class="list-group">
            {% for nature in natures %}
            <li class="list-group-item">
                <div class="col-11 form-floating mx-auto"
                    style="display: flex;justify-content: space-between;align-items: center;">
                    <span>{{ nature.name_nature }}</span>
                    <div>
                        <a 
                            hx-get="{{ url_for('nature.edit_nature', id_nature=nature.id) }}"
                            hx-target="#modal-content"
                            data-bs-toggle="modal" data-bs-target="#nature-modal" 
                            class="btn btn-primary bi bi-pencil-square"></a>
                        <a 
                            hx-get="{{ url_for('nature.warning_nature', id_nature=nature.id) }}"
                            hx-target="#modal-content" data-bs-toggle="modal" data-bs-target="#nature-modal"
                            class="btn btn-danger bi bi-x-lg"></a>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
        <a hx-get="{{ url_for('nature.render_form') }}" class="btn btn-primary mt-3 col-6 mx-auto"
            hx-target="#modal-content" data-bs-toggle="modal" data-bs-target="#nature-modal">
            Adicionar Natureza
        </a>
    </div>
</div>

<div class="modal fade" id="nature-modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body" id="modal-content"></div>
        </div>
    </div>
</div>

{% endblock %}